.PHONY: clean All

All:
	@echo "----------Building project:[ transpose - Debug ]----------"
	@cd "transpose" && "$(MAKE)" -f  "transpose.mk"
clean:
	@echo "----------Cleaning project:[ transpose - Debug ]----------"
	@cd "transpose" && "$(MAKE)" -f  "transpose.mk" clean
